name: Release

on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        uses: ./.github/actions/execute-gradle
        with:
          gradle-commands: 'build'

      - name: Rollback release
        if: ${{ failure() || cancelled() }}
        uses: ./.github/actions/delete-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test
        shell: bash
        run: exit 24
#        uses: ./.github/actions/execute-gradle
#        with:
#          gradle-commands: 'test'
      - name: Rollback release
        if: ${{ failure() || cancelled() }}
        uses: ./.github/actions/delete-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure Git
        uses: ./.github/actions/configure-git
        with:
          user-name: ${{ secrets.USER_NAME }}
          user-mail: ${{ secrets.USER_MAIL }}

      - name: Extract versions
        uses: ./.github/actions/extract-version

      - name: Extract branch
        uses: ./.github/actions/extract-branch

      - name: Update versions
        uses: ./.github/actions/update-versions
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create branches
        id: create-branches
        shell: bash
        run: exit 123
#        uses: ./.github/actions/create-branches
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        uses: ./.github/actions/publish-package
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch: release/${{ env.VERSION }}

      - name: Rollback release
        if: ${{ failure() || cancelled() }}
        uses: ./.github/actions/delete-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rollback branches
        needs: create-branches
        if: ${{ failure() || cancelled() }}
        uses: ./.github/actions/delete-branches
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
